# Generated by Django 3.1.3 on 2020-11-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0002_auto_20201128_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.URLField(max_length=100),
        ),
    ]
